name: VueBuild

on:
  push:
    branches:
      - master

  # Build images on PRs.
  pull_request:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        run: sh deploy.sh
